# Generated by Django 5.1 on 2024-10-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=10)),
                ('scheme_name', models.CharField(max_length=50)),
                ('scheme_id', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=15)),
                ('phno1', models.IntegerField()),
                ('phno2', models.IntegerField()),
                ('aadhaar', models.CharField(max_length=50)),
                ('pan', models.CharField(max_length=50)),
                ('wt_conversion', models.CharField(max_length=50)),
                ('metal', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('installment', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('nominee_name', models.CharField(max_length=50, null=True)),
                ('nominee_email', models.EmailField(max_length=254, null=True)),
                ('nominee_phone_no', models.CharField(max_length=50, null=True)),
                ('nominee_dob', models.CharField(max_length=50, null=True)),
                ('referral_name', models.CharField(max_length=50, null=True)),
                ('referral_number', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
