# Generated by Django 5.1 on 2024-10-14 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purity', models.CharField(max_length=50)),
                ('rate_10_grams', models.IntegerField()),
                ('rate_1_gram', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trasaction_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('voucher_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('transaction', models.CharField(max_length=50)),
                ('receipt_date', models.DateField()),
                ('receipt_time', models.TimeField(auto_now=True)),
                ('receipt_amount', models.IntegerField()),
                ('member_name', models.CharField(max_length=50)),
                ('member_number', models.CharField(max_length=50)),
                ('member_group', models.CharField(max_length=50)),
                ('total_amount', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
                ('ent_by', models.CharField(max_length=50)),
                ('installment_in_grams', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('group', models.CharField(max_length=10, null=True)),
                ('scheme_name', models.CharField(max_length=50, null=True)),
                ('scheme_id', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pin', models.CharField(max_length=15, null=True)),
                ('phno1', models.IntegerField(null=True)),
                ('phno2', models.IntegerField(null=True)),
                ('aadhaar', models.CharField(max_length=50, null=True)),
                ('pan', models.CharField(max_length=50, null=True)),
                ('wt_conversion', models.CharField(max_length=50, null=True)),
                ('metal', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('installment', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('nominee_name', models.CharField(max_length=50, null=True)),
                ('nominee_email', models.EmailField(max_length=254, null=True)),
                ('nominee_phone_no', models.CharField(max_length=50, null=True)),
                ('nominee_dob', models.CharField(max_length=50, null=True)),
                ('referral_name', models.CharField(max_length=50, null=True)),
                ('referral_number', models.CharField(max_length=50, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
