# Generated by Django 5.1.1 on 2024-10-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='referral_points',
            field=models.IntegerField(default=0),
        ),
    ]
