# Generated by Django 5.1.1 on 2024-10-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='nominee_dob',
        ),
    ]
