# Generated by Django 5.1 on 2024-10-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='installment_in_grams',
            field=models.FloatField(),
        ),
    ]
