# Generated by Django 5.1.1 on 2024-10-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='nominee_phone_no',
        ),
        migrations.AddField(
            model_name='member',
            name='nominee_phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='scheme_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
