# Generated by Django 5.1.1 on 2024-10-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_member_nominee_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nominee_dob',
            field=models.DateField(null=True),
        ),
    ]
